import pandas as pd 
import matplotlib.pyplot as plt
df = pd.read_csv("NetflixData.csv")
df = df.dropna(subset=["index","show_id","type","title","director","cast","country","date_added","release_year","rating","duration","listed_in","description"])
type_count = df['type'].value_counts()
plt.figure(figsize=(6,4))
plt.bar(type_count.index, type_count.values, color=['skyblue','orange'] )
plt.title("number of movies Vs Tv shows on Netflix")
plt.xlabel("Type")
plt.ylabel("count")

plt.tight_layout()
plt.savefig("Movies_vs_Tvshows.png")
plt.show()  


rating_count = df['rating'].value_counts()
plt.figure(figsize=(8,6))
plt.pie(rating_count, labels = rating_count.index,autopct='%1.1f%%',startangle=90)
plt.title("Percentage of content ratings")
plt.tight_layout()
plt.savefig("Content_ratings_pie.png")
plt.show()

movie_df = df[df['type']=='Movie'].copy()
movie_df['duration_int'] = movie_df['duration'].str.replace('min','').astype(int)
plt.figure(figsize=(8,6))
plt.hist(movie_df['duration_int'],bins=30, color='purple',edgecolor='black')
plt.title("Duration of movie")
plt.xlabel("Duration(minurtes)")
plt.ylabel("Number of movies")
plt.tight_layout()
plt.savefig('movie_duration_histogram.png')
plt.show()


country_counts = df['country'].value_counts().head(10)
plt.figure(figsize=(8,6))
plt.barh(country_counts.index, country_counts.values,color='teal')
plt.title("Top 10 countries ny Number od shows")
plt.xlabel("Number of shows")
plt.ylabel("Country")
plt.tight_layout()
plt.savefig("top10_countries.png")
plt.grid()
plt.show()
